#!/bin/bash

echo "================================================================================================================================="
echo "The launcher script is now deprecated. Please see https://github.com/haiwen/seafile-docker/blob/master/upgrade_from_old_format.md"
echo "================================================================================================================================="
echo
echo "Or run this command directly:"
echo
echo "   docker rm -f seafile"
echo "   docker run -d -it --name seafile -v $PWD/shared:/shared -p 80:80 -p 443:443 seafileltd/seafile"
echo
echo "================================================================================================================================="
